CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL IDENTITY,
	[Name] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NULL, 
    [Email] NVARCHAR(100) NULL UNIQUE,
	[Password] NVARCHAR(50) NOT NULL,
	[RoleId] INT NOT NULL,
	[CreatedOn] DATE NOT NULL DEFAULT(GETDATE())
	
	CONSTRAINT PK_User_Id PRIMARY KEY (Id)
	CONSTRAINT FK_User_RoleId_Role_Id FOREIGN KEY (RoleId) REFERENCES [nom].[Role](Id)
)

